services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data: